name: Github Actions 실행

on:
  push:
    branches:
    - main
env:
  NAME: kosa
  USERNAME: kosa
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
  
      
jobs:
  my-Deploy-Job:
    runs-on: ubuntu-latest
  
  my-Deploy-job2
    name: 배포작업
    runs-on" self-hosted

    
    steps: 
      - name: Hello World 찍기 # Step에 이름 붙이는 기능
        run: echo "Hello World" # 실행시킬 명령어 작성
      
      - name: 배포작업 1ㄱ단단계 파일생성
        run: echo "hellow World" > output.txt

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"
          
      - name: 작업폴더가 무엇인지 출력
        run: pwd
          
      - name: 작업폴더 목록 확인
        run: ls -la

      - name: 환경 변수 모두 출력
        run: env

      - name: 환경변수 name 출력
        run: echo ${{env.NAME }}
      - name: 환경변수 name 출력
        run: echo ${{env.USERNAME }}
      - name: 시크릿 USER_PASSWORD 출력
        run: |
          echo "USER_PASSWORD = ${{ env.USER_PASSWORD }}"
          
          echo "USER_PASSWORD = ${{ secrets.USER_PASSWORD }}"

      
